## Clean Weather Data

In [ ]:
%%sql

In [51]:
import pandas as pd

In [52]:
df =  pd.read_csv('/home/entity/PycharmProjects/PythonProject1/Sustainability/Data/Road traffic nationwide py/ogd-smn_gre_d_historical.csv',sep=";")#header=None#)
#print(df.head())


df

,station_abbr,reference_timestamp,tre200d0,tre200dx,tre200dn,tre005d0,tre005dx,tre005dn,ure200d0,pva200d0,...,osr000d0,ods000d0,sre000d0,sremaxdv,erefaod0,xcd000d0,dkl010d0,xno000d0,xno012d0,rreetsd0
0,GRE,15.05.1992 00:00,19.0,28.7,8.2,NaN,NaN,NaN,63.3,12.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
1,GRE,16.05.1992 00:00,19.7,28.5,9.2,NaN,NaN,NaN,58.0,12.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
2,GRE,17.05.1992 00:00,18.6,24.9,11.3,NaN,NaN,NaN,67.5,14.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
3,GRE,18.05.1992 00:00,17.3,23.4,9.6,NaN,NaN,NaN,47.1,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
4,GRE,19.05.1992 00:00,16.3,22.5,9.4,NaN,NaN,NaN,45.1,8.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11892,GRE,27.12.2024 00:00,-1.7,-0.8,-3.0,NaN,NaN,NaN,99.4,5.4,...,NaN,NaN,0.0,0.0,0.2,0.0,236.0,21.7,13.7,0.0
11893,GRE,28.12.2024 00:00,-0.9,-0.6,-1.3,NaN,NaN,NaN,99.5,5.7,...,NaN,NaN,0.0,0.0,0.2,0.0,233.0,20.9,12.9,0.0
11894,GRE,29.12.2024 00:00,-1.0,-0.7,-1.3,NaN,NaN,NaN,99.6,5.7,...,NaN,NaN,0.0,0.0,0.2,0.0,236.0,21.0,13.0,0.0
11895,GRE,30.12.2024 00:00,-1.6,-1.2,-2.1,NaN,NaN,NaN,99.6,5.4,...,NaN,NaN,0.0,0.0,0.2,0.0,238.0,21.6,13.6,0.0
11896,GRE,31.12.2024 00:00,-1.3,-0.8,-2.0,NaN,NaN,NaN,99.6,5.5,...,NaN,NaN,0.0,0.0,0.2,0.0,234.0,21.3,13.3,0.0

In [70]:

    column_mapping = {
    'reference_timestamp':'timestamp',
    'station_abbr':'station',
    'tre200d0': 'Temp_dly_avg',
    'tre200dx': 'Temp_dly_max',
    'tre200dn': 'Temp_dly_min',
    'ure200d0': 'Humid_dly_avg',
    'pva200d0': 'Vapor_dly_avg',
    #'erefaod0': 'Evap_dly_total_mmd',
    #'dkl010d0': 'Wind_dly_mean'
}
    #df = df[list(column_mapping.keys())].rename(columns=column_mapping)
    df.columns

Index(['timestamp', 'station', 'Temp_dly_avg', 'Temp_dly_max', 'Temp_dly_min',
       'Humid_dly_avg', 'Vapor_dly_avg'],
      dtype='object')

In [81]:
dfdw2 = pd.read_csv('/home/entity/PycharmProjects/PythonProject1/Sustainability/Data/weather data/ogd-smn_wyn_d_historical.csv',sep=";")
#dfdw2.dropna(axis=1, how='all', inplace=True)
dfdw2

,station_abbr,reference_timestamp,tre200d0,tre200dx,tre200dn,tre005d0,tre005dx,tre005dn,ure200d0,pva200d0,...,osr000d0,ods000d0,sre000d0,sremaxdv,erefaod0,xcd000d0,dkl010d0,xno000d0,xno012d0,rreetsd0
0,WYN,01.01.1978 00:00,1.5,5.8,-0.2,NaN,NaN,NaN,85.2,5.6,...,NaN,NaN,318,75,NaN,NaN,NaN,NaN,NaN,NaN
1,WYN,02.01.1978 00:00,-0.9,2.4,-3.5,NaN,NaN,NaN,98.2,5.7,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
2,WYN,03.01.1978 00:00,3.4,6.3,0.4,NaN,NaN,NaN,79.8,6.4,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
3,WYN,04.01.1978 00:00,2.2,3.3,0.5,NaN,NaN,NaN,74.1,5.2,...,NaN,NaN,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,WYN,05.01.1978 00:00,-0.8,3.7,-3.8,NaN,NaN,NaN,82.5,4.7,...,NaN,NaN,228,53,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17162,WYN,27.12.2024 00:00,-1.7,-0.5,-3.3,-1.5,0.1,-3.2,92.3,5.0,...,NaN,NaN,0,0,0.2,0.0,242.0,21.7,13.7,0.0
17163,WYN,28.12.2024 00:00,-1.2,-0.1,-2.3,-1.0,0.7,-2.2,94.6,5.3,...,NaN,NaN,0,0,0.2,0.0,216.0,21.2,13.2,0.0
17164,WYN,29.12.2024 00:00,-1.4,-0.4,-2.1,-1.1,0.7,-1.8,95.0,5.2,...,NaN,NaN,0,0,0.2,0.0,216.0,21.4,13.4,0.0
17165,WYN,30.12.2024 00:00,-2.2,-1.3,-3.2,-1.8,-0.4,-2.8,94.4,4.9,...,NaN,NaN,0,0,0.2,0.0,198.0,22.2,14.2,0.0
17166,WYN,31.12.2024 00:00,-1.8,-0.7,-2.9,-1.4,0.4,-2.7,93.9,5.0,...,NaN,NaN,0,0,0.2,0.0,217.0,21.8,13.8,0.0

In [82]:
column_mapping2 = {
    'station_abbr':'station',
    'reference_timestamp':'timestamp',
    'tre200d0': 'Temp_dly_avg',
    'tre200dx': 'Temp_dly_max',
    'tre200dn': 'Temp_dly_min',
    'tre005d0': 'Fl_Temp_dly_avg',
    "tre005dx": "Fl_Temp_dly_max",
    "tre005dn": "Fl_Temp_dly_min",
    'ure200d0': 'Humid_dly_avg',
    'pva200d0': 'Vapor_dly_avg',
    'erefaod0': 'Evap_dly_total_mmd',
    'dkl010d0': 'Wind_dly_mean',
    'rka150d0': 'Rain_dly_ttl'}
dfdw2
dfdw2 = dfdw2[list(column_mapping2.keys())].rename(columns=column_mapping2)
dfdw2.columns

Index(['station', 'timestamp', 'Temp_dly_avg', 'Temp_dly_max', 'Temp_dly_min',
       'Fl_Temp_dly_avg', 'Fl_Temp_dly_max', 'Fl_Temp_dly_min',
       'Humid_dly_avg', 'Vapor_dly_avg', 'Evap_dly_total_mmd', 'Wind_dly_mean',
       'Rain_dly_ttl'],
      dtype='object')

In [83]:
dfdw2

,station,timestamp,Temp_dly_avg,Temp_dly_max,Temp_dly_min,Fl_Temp_dly_avg,Fl_Temp_dly_max,Fl_Temp_dly_min,Humid_dly_avg,Vapor_dly_avg,Evap_dly_total_mmd,Wind_dly_mean,Rain_dly_ttl
0,WYN,01.01.1978 00:00,1.5,5.8,-0.2,NaN,NaN,NaN,85.2,5.6,NaN,NaN,NaN
1,WYN,02.01.1978 00:00,-0.9,2.4,-3.5,NaN,NaN,NaN,98.2,5.7,NaN,NaN,NaN
2,WYN,03.01.1978 00:00,3.4,6.3,0.4,NaN,NaN,NaN,79.8,6.4,NaN,NaN,NaN
3,WYN,04.01.1978 00:00,2.2,3.3,0.5,NaN,NaN,NaN,74.1,5.2,NaN,NaN,NaN
4,WYN,05.01.1978 00:00,-0.8,3.7,-3.8,NaN,NaN,NaN,82.5,4.7,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17162,WYN,27.12.2024 00:00,-1.7,-0.5,-3.3,-1.5,0.1,-3.2,92.3,5.0,0.2,242.0,0.0
17163,WYN,28.12.2024 00:00,-1.2,-0.1,-2.3,-1.0,0.7,-2.2,94.6,5.3,0.2,216.0,0.0
17164,WYN,29.12.2024 00:00,-1.4,-0.4,-2.1,-1.1,0.7,-1.8,95.0,5.2,0.2,216.0,0.0
17165,WYN,30.12.2024 00:00,-2.2,-1.3,-3.2,-1.8,-0.4,-2.8,94.4,4.9,0.2,198.0,0.0
17166,WYN,31.12.2024 00:00,-1.8,-0.7,-2.9,-1.4,0.4,-2.7,93.9,5.0,0.2,217.0,0.0

In [84]:
# Extract just the date part from the string before converting
dfdw2['timestamp'] = dfdw2['timestamp'].str.split(' ').str[0]
dfdw2['timestamp'] = pd.to_datetime(dfdw2['timestamp'], format='%d.%m.%Y')

# Then filter
dfdw2 = dfdw2[dfdw2['timestamp'].dt.year >= 2008]

In [85]:
dfdw2

,station,timestamp,Temp_dly_avg,Temp_dly_max,Temp_dly_min,Fl_Temp_dly_avg,Fl_Temp_dly_max,Fl_Temp_dly_min,Humid_dly_avg,Vapor_dly_avg,Evap_dly_total_mmd,Wind_dly_mean,Rain_dly_ttl
10957,WYN,2008-01-01,-1.2,0.1,-4.0,-1.4,-0.3,-4.1,86.6,4.8,0.3,63.0,0.0
10958,WYN,2008-01-02,-2.1,-1.3,-3.0,-2.0,0.1,-3.4,73.6,3.8,0.6,51.0,0.0
10959,WYN,2008-01-03,-2.5,0.9,-4.6,-3.2,4.1,-7.2,78.0,3.9,0.3,60.0,0.0
10960,WYN,2008-01-04,-1.6,0.9,-4.9,-2.4,1.2,-6.8,85.5,4.7,0.3,135.0,0.0
10961,WYN,2008-01-05,2.1,5.2,-1.1,1.4,6.2,-1.7,92.4,6.6,0.3,214.0,16.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
17162,WYN,2024-12-27,-1.7,-0.5,-3.3,-1.5,0.1,-3.2,92.3,5.0,0.2,242.0,0.0
17163,WYN,2024-12-28,-1.2,-0.1,-2.3,-1.0,0.7,-2.2,94.6,5.3,0.2,216.0,0.0
17164,WYN,2024-12-29,-1.4,-0.4,-2.1,-1.1,0.7,-1.8,95.0,5.2,0.2,216.0,0.0
17165,WYN,2024-12-30,-2.2,-1.3,-3.2,-1.8,-0.4,-2.8,94.4,4.9,0.2,198.0,0.0
17166,WYN,2024-12-31,-1.8,-0.7,-2.9,-1.4,0.4,-2.7,93.9,5.0,0.2,217.0,0.0

In [119]:
dfdw2.to_excel('Weather_WYN_Daily.xlsx', index=False, engine='openpyxl')

## Cleaning and combining hourly weather datasets since 2008

In [106]:
dfhw2008 = pd.read_csv('/home/entity/PycharmProjects/PythonProject1/Sustainability/Data/weather data/ogd-smn_wyn_h_historical_2000-2009.csv',sep=";")
dfhw2008
dfhw2008 = dfhw2008[list(column_mapping_hourly.keys())].rename(columns=column_mapping_hourly)
dfhw2008.columns

Index(['station', 'timestamp', 'Temp_hly_avg', 'Temp_hly_max', 'Temp_hly_min',
       'Fl_Temp_hly_avg', 'Fl_Temp_hly_min', 'Humid_hly_avg', 'Vapor_hly_avg',
       'Evap_hly_total_mmd', 'Wind_hly_mean', 'Rain_hly_ttl'],
      dtype='object')

In [108]:
column_mapping_hourly = {
    'station_abbr': 'station',
    'reference_timestamp': 'timestamp',
    'tre200h0': 'Temp_hly_avg',
    'tre200hx': 'Temp_hly_max',
    'tre200hn': 'Temp_hly_min',
    'tre005h0': 'Fl_Temp_hly_avg',
    'tre005hn': 'Fl_Temp_hly_min',
    'ure200h0': 'Humid_hly_avg',
    'pva200h0': 'Vapor_hly_avg',
    'erefaoh0': 'Evap_hly_total_mmd',
    'dkl010h0': 'Wind_hly_mean',
    'rre150h0': 'Rain_hly_ttl'
}

In [109]:
dfhw2008 = dfhw2008[list(column_mapping_hourly.keys())].rename(columns=column_mapping_hourly)
dfhw2008.columns

KeyError: "None of [Index(['station_abbr', 'reference_timestamp', 'tre200h0', 'tre200hx',\n       'tre200hn', 'tre005h0', 'tre005hn', 'ure200h0', 'pva200h0', 'erefaoh0',\n       'dkl010h0', 'rre150h0'],\n      dtype='object')] are in the [columns]"

In [110]:
dfhw2008

,station,timestamp,Temp_hly_avg,Temp_hly_max,Temp_hly_min,Fl_Temp_hly_avg,Fl_Temp_hly_min,Humid_hly_avg,Vapor_hly_avg,Evap_hly_total_mmd,Wind_hly_mean,Rain_hly_ttl
0,WYN,01.01.2000 00:00,-0.3,-0.2,-0.4,0.3,0.2,83.5,5.0,NaN,225.0,0.0
1,WYN,01.01.2000 01:00,-0.2,-0.1,-0.3,0.3,0.3,84.2,5.1,NaN,214.0,0.0
2,WYN,01.01.2000 02:00,-0.1,0.1,-0.3,0.4,0.4,84.3,5.1,NaN,209.0,0.0
3,WYN,01.01.2000 03:00,-0.1,0.1,-0.2,0.4,0.3,83.9,5.1,NaN,217.0,0.0
4,WYN,01.01.2000 04:00,0.0,0.1,-0.1,0.3,0.2,84.9,5.2,NaN,226.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
87671,WYN,31.12.2009 19:00,3.6,3.7,3.4,3.1,3.0,99.6,7.8,NaN,90.0,0.0
87672,WYN,31.12.2009 20:00,3.7,4.1,3.2,2.9,2.5,98.4,7.8,NaN,180.0,0.0
87673,WYN,31.12.2009 21:00,3.7,3.7,3.6,3.3,3.3,98.8,7.8,NaN,68.0,0.0
87674,WYN,31.12.2009 22:00,4.0,4.1,3.8,3.5,3.5,97.2,7.9,NaN,135.0,0.0
87675,WYN,31.12.2009 23:00,3.7,3.8,3.6,3.4,3.4,100.0,8.0,NaN,59.0,0.0

In [115]:
# Convert to datetime while preserving time information
dfhw2008['timestamp'] = pd.to_datetime(dfhw2008['timestamp'], format='%d.%m.%Y %H:%M')

# Filter for year 2008 only
dfhw2008 = dfhw2008[dfhw2008['timestamp'].dt.year == 2008]

# Reset index
dfhw2008 = dfhw2008.reset_index(drop=True)

df2008 =dfhw2008

In [117]:
df2010_19 = pd.read_csv('/home/entity/PycharmProjects/PythonProject1/Sustainability/Data/weather data/ogd-smn_wyn_h_historical_2010-2019.csv',sep=";")
df2010_19 = df2010_19[list(column_mapping_hourly.keys())].rename(columns=column_mapping_hourly)
df2010_19.columns
df2020_24 = pd.read_csv('/home/entity/PycharmProjects/PythonProject1/Sustainability/Data/weather data/ogd-smn_wyn_h_historical_2010-2019.csv',sep=";")
df2020_24 = df2020_24[list(column_mapping_hourly.keys())].rename(columns=column_mapping_hourly)
df2020_24.columns

Index(['station', 'timestamp', 'Temp_hly_avg', 'Temp_hly_max', 'Temp_hly_min',
       'Fl_Temp_hly_avg', 'Fl_Temp_hly_min', 'Humid_hly_avg', 'Vapor_hly_avg',
       'Evap_hly_total_mmd', 'Wind_hly_mean', 'Rain_hly_ttl'],
      dtype='object')

In [120]:
Weather_WYN_hourly = pd.concat([df2008, df2010_19, df2020_24], ignore_index=True)
Weather_WYN_hourly.to_excel('Weather_WYN_Hourly.xlsx', index=False, engine='openpyxl')